default_stages: [commit]

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff check
        name: ruff check
        entry: ruff check --select I --fix src
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff format
        name: ruff format
        entry: ruff format src
        language: system
        always_run: true
        pass_filenames: false

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
