services:
  clean_arch_database:
    image: postgres:16.3-alpine3.20
    container_name: clean_arch_database
    environment:
      - POSTGRES_DB=clean_arch_database
      - POSTGRES_USER=clean_arch_user
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "clean_arch_database"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432

  clean_arch_app:
    image: clean_arch_app
    build: .
    container_name: clean_arch_app
    env_file: docker-compose.env
    ports:
      - 8000:8000
    depends_on:
      clean_arch_database:
        condition: service_healthy
    volumes:
      - ./:/app
